from pathlib import Path

ROOT = Path(__file__).resolve().parent

SEQ_LEN = 16
VOCAB_SIZE = 128
MIDI_DIR = ROOT / "midis"
EXPERT_CACHE = ROOT / "data" / "expert.npz"
OUTPUT_DIR = ROOT / "output"
CHECKPOINT_DIR = ROOT / "checkpoints"
CHECKPOINT_PATH = CHECKPOINT_DIR / "ppo.pt"

QUANTIZE_SEC = 0.25
COUNTRY_FILTER = None  # e.g. "England" to filter by country folder

N_AIRL_ITERS = 100
DISC_EPOCHS = 5
BATCH_SIZE = 64
PPO_TIMESTEPS = 2048
PPO_LR = 3e-4
PPO_GAMMA = 0.99
PPO_GAE_LAMBDA = 0.95
PPO_CLIP = 0.2
PPO_EPOCHS = 10
PPO_MINIBATCH = 64
PPO_VF_COEF = 0.5
PPO_MAX_GRAD_NORM = 0.5
PPO_HIDDEN = 128
AGENT_COLLECT_STEPS = 1024
DISC_LR = 3e-4
PPO_ENT_COEF = 0.02
ENV_MAX_STEPS = 100

MIN_SEQUENCE_LENGTH = SEQ_LEN + 1
